name: The Pulse
favicon: null
layout_spectrum: 0.9428594091441482
typography_spectrum: 0.7400205668527633
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.5584361404180527
  lightness: 0.6226196531206369
  saturation: 0.985535355983302
  rhythmicContrast: 0.3613574649207294
purpose: []
